# Changes here will be overwritten by Copier
_commit: 0ddd376
_src_path: ../../templates/base
add_extension: python
email: t.paine154@gmail.com
github: airflow-laminar
project_description: Supervisor operators and configuration for long-running tasks
project_name: airflow-supervisor
python_version_primary: '3.11'
team: the airflow-supervisor authors
