# @package _global_

defaults:
  # https://hydra.cc/docs/configure_hydra/logging/
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom
  - _self_

_target_: airflow_supervisor.SupervisorConfiguration
unix_http_server:
inet_http_server:
supervisord:
supervisorctl:
include:
program:
group:
fcgiprogram:
eventlistener:
rpcinterface:
